//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScannerGB.Data.Providers.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScannerGBDatabaseFirstContext : DbContext
    {
        public ScannerGBDatabaseFirstContext()
            : base("name=ScannerGBDatabaseFirstContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Additional> Additionals { get; set; }
        public virtual DbSet<DocType> DocTypes { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
