//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScannerGB.Data.Providers.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public int OwnerId { get; set; }
        public bool IsShared { get; set; }
        public int DocTypeId { get; set; }
        public string DocAddress { get; set; }
    
        public virtual DocType DocType { get; set; }
        public virtual User User { get; set; }
    }
}
